"""Constant for use throught FRC2481 2024 Robot"""
SWERVE_FRONT_LEFT_DRIVE_MOTOR_CAN_ID = 1
SWERVE_FRONT_LEFT_STEER_MOTOR_CAN_ID = 2
SWERVE_FRONT_RIGHT_DRIVE_MOTOR_CAN_ID = 3
SWERVE_FRONT_RIGHT_STEER_MOTOR_CAN_ID = 4
SWERVE_BACK_LEFT_DRIVE_MOTOR_CAN_ID =5
SWERVE_BACK_LEFT_STEER_MOTOR_CAN_ID = 6
SWERVE_BACK_RIGHT_DRIVE_MOTOR_CAN_ID = 7
SWERVE_BACK_RIGHT_STEER_MOTOR_CAN_ID = 8
SHOOTER_MOTOR_CAN_ID = 9
INTAKE_VERTICAL_MOTOR_CAN_ID = 10
INTAKE_HORIZONTAL_MOTOR_CAN_ID = 11
FEEDER_MOTOR_CAN_ID = 12
ELEVATOR_MOTOR_CAN_ID = 13
SWERVE_FRONT_LEFT_STEER_ENCODER_CAN_ID = 2
SWERVE_FRONT_RIGHT_STEER_ENCODER_CAN_ID = 4
SWERVE_BACK_LEFT_STEER_ENCODER_CAN_ID = 6
SWERVE_BACK_RIGHT_STEER_ENCODER_CAN_ID = 8
PIGEON_GYRO_CAN_ID = 1

#drivetrain
DRIVE_WHEEL_TRACK = 0
DRIVE_WHEEL_BASE = 0
DRIVE_P = 0
DRIVE_I = 0
DRIVE_D = 0
DRIVE_F = 0
DRIVE_PERIOD = 20 # milliseconds?
DRIVE_MAX_SPEED = 60

#steer
STEER_P = 0
STEER_I = 0
STEER_D = 0
STEER_F = 0

SWERVE_REDUCTION_STEER = 40
SWERVE_REDUCTION_DRIVE = 4.31

DRIVER_CONTROLLER_PORT = 0
OPERATOR_CONTROLLER_PORT = 1

#Feeder
FEEDER_SPEED = .70

#BeamBrake
INTAKE_BEAM_BREAK_PORT = 8
#FEEDER_BEAM_BREAK_PORT = 9

#ShooterFocCurrentGains
SHOOTER_SPEED_RPS = 50
SHOOTER_P = 0
SHOOTER_I = 0
SHOOTER_D = 0
SHOOTER_F = 0
SHOOTER_PEAK_CURRENT = 0

#Gripper
GRIPPER_SOLENOID_MODULE = 1
GRIPPER_SOLENOID_MODULE_TYPE = 2
GRIPPER_DOUBLE_SOLENOID_REVERSE_PORT = 1
GRIPPER_DOUBLE_SOLENOID_FORWARD_PORT = 0

#Arm
ARM_SOLENOID_MODULE = 4
ARM_SOLENOID_MODULE_TYPE = 5
ARM_DOUBLE_SOLENOID_FORWARD_PORT = 6
ARM_DOUBLE_SOLENOID_REVERSE_PORT = 7
